jasypt:
  encryptor:
    password: ${ENC_KEY:}
    algorithm: PBEWITHMD5ANDTRIPLEDES
    stringOutputType: base64

spring:
  flyway:
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true
    out-of-order: true
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    hikari:
      connection-timeout: 60000

security:
  jwt:
    expirationMinutes: 43200
    signing:
      key: ${JWT_SIGNING_KEY:}
  password:
    reset:
      validityMinutes: 15

services:
  sendgrid:
    api-key: ${SENDGRID_API_KEY:}

app:
  domain: http://localhost:8080

logging:  
  level:    
    org.flywaydb: DEBUG